### ISSUE TITLE
not support gtceu 1.0.20

### ISSUE THREAD

**Issue by bobyasasas** [YiRanMushroom/GTCEuAO#1]
minecraft crashed when use gtceu-forge-1.20.1-1.0.20 and gtceuao-1.20.1-1.2.0. I tried gtceu-forge-1.20.1-1.0.20.b and it worked fine.
forge version: 47.2.17
mod list: 
gtceu
gtceuao
[错误报告-2024-1-16_1.49.46.zip](https://github.com/YiRanMushroom/gtceuao/files/13941679/-2024-1-16_1.49.46.zip)

**Comment by YiRanMushroom** [comment]
I think you should just use the new version of that, the newest version is on github. They added some machines in the newer version. My mixin is just basically disabled the original recipes , and register the recipe for them, in 1.0.20.b, there are some machine which 1.0.20 doesn't. So my mixin just registered the recipe for that machine which doesn't exist in 1.0.20, which caused the crash.

BTW, I think the newest version of gregtech may have some bug because I can't launch with it (only gregtech) somehow, could you help me to check?

**Comment by YiRanMushroom** [comment]
Maybe I should simply add the recipe instead of change it

**Comment by YiRanMushroom** [comment]
Nevermined that should be my fault

**Comment by YiRanMushroom** [comment]
I don't know what but this could potentially cause severe bug, so I will private this just for now, I will try to fix this later

**Comment by YiRanMushroom** [comment]
Try this then
https://github.com/YiRanMushroom/GTCEuAO/releases/download/v1.2.1/gtceuao-1.20.1-1.2.1.jar
it should be fixed

**Comment by bobyasasas** [comment]
Thanks.
Different release of gtceu-1.0.20.b seems have different mixin. In some release I even cant open my minecraft. I think it may be better  to change  recipes  before check it if is on game like some mods. but i regretfully dont know how to do it. you seem have fixed it in 1.2.1 release. I will try it later. As for version, my suggest is use the public version of curseforge and modrich as the github may have many bugs and update frequently. It also good to add version check in mods.toml with  [[dependencies.${modid}]] and version optional.

**Comment by YiRanMushroom** [comment]
I genuinely cannot be bothered to config the gradlew, I always have difficulties in denpendency solving, and I just learned mixin and how to code after 1.12.2, so basically I need to improve it step by step.

I can use realease versions of gregtech but the decomp code is hard to read so I still need to download the source code on github.

I will try to add denpendency in mods.toml, but I need to learn. However, I also use mixin injection in my mod, so it's impossible for me to make it compatible in all versions, it is now compatible with 1.0.20b. I will not try to make it compatible with lower version than 1.0.20b. However, I will still try to support current version when updating this mod to future version of GregTech.
