### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by 3453890470** [YiRanMushroom/GTCEuAO#11]
https://mclo.gs/hY3Ti5E
相关冲突mod：[Steam Additions](https://www.curseforge.com/projects/1008510)

**Comment by 3453890470** [comment]
如果不装任何一方的mod都能正常进入游戏

**Comment by YiRanMushroom** [comment]
I don't think it's my fault. 你用的steamadditions是什么版本的，我本身使用steamadditions就进不了游戏，出现NoSuchMethodError，你确定不使用我的模组可以正常运行吗

**Comment by YiRanMushroom** [comment]
1.0版本无论如何都会崩溃，1.1版本本身作者打包有问题，机器都不加载。
之前GTCEu更新了注册方式，我之前也崩，之后我更新好了，现在这个模组报一样的问题，我觉得应该和我没什么关系。

**Comment by 3453890470** [comment]
1.1可以正常进入游戏

**Comment by 3453890470** [comment]
> 如果不装任何一方的mod都能正常进入游戏

大概就是这个情况

**Comment by 3453890470** [comment]
很奇妙

**Comment by YiRanMushroom** [comment]
1.0不装我的也进不去

**Comment by 3453890470** [comment]
1.1单独装可以进游戏
1.0我也进不去游戏

**Comment by YiRanMushroom** [comment]
1.1和我的一块装可以进游戏的呀，你在试一试。
不过我觉得他的1.1版本不对，你看他有正确注册内容吗，他的机器没添加上

**Comment by YiRanMushroom** [comment]
我的请用最后一个release的

**Comment by 3453890470** [comment]
使用的是最新了的2.2.2的

**Comment by 3453890470** [comment]
很奇怪

**Comment by 3453890470** [comment]
我再试一下

**Comment by YiRanMushroom** [comment]
我的要使用3.0.0-build20，GTM是gtceu-1.20.1-1.2.1

**Comment by YiRanMushroom** [comment]
这是curseforge上最新版本了

**Comment by 3453890470** [comment]
草，2.2.2的排在3.0.0后面

**Comment by 3453890470** [comment]
敢情只是我下错了版本

**Comment by 3453890470** [comment]
我再试一下

**Comment by 3453890470** [comment]
还是不行

**Comment by 3453890470** [comment]
https://mclo.gs/2mA7Uml

**Comment by 3453890470** [comment]
新的

**Comment by 3453890470** [comment]
https://mclo.gs/8isCQYz

**Comment by 3453890470** [comment]
log

**Comment by YiRanMushroom** [comment]
我仔细看看

**Comment by 3453890470** [comment]
坏了

**Comment by 3453890470** [comment]
没开steamadd都会崩

**Comment by 3453890470** [comment]
https://mclo.gs/bzNK3TM

**Comment by YiRanMushroom** [comment]
估计是你GTM版本不对，他有1.19.2有1.20.1的，我的Mixin是可以成功注入这个版本的：https://www.curseforge.com/minecraft/mc-mods/gregtechceu-modern/files/5311877 你换成这个试试。

我看刚刚错误是发现gregtech找不到heatCoilOverclockingLogic，你换成这个版本试一下

**Comment by 3453890470** [comment]
草

**Comment by YiRanMushroom** [comment]
<img width="919" alt="image" src="https://github.com/YiRanMushroom/GTCEuAO/assets/114495322/895e6656-3a47-4a22-97d8-5fd8a14d76ab">

你的这个版本不是和我开发的匹配的

**Comment by 3453890470** [comment]
用的是整合包专供版本
