### ISSUE TITLE
Crushed with gtceu-1.20.1-1.2.1-build_642.jar

### ISSUE THREAD

**Issue by woetal** [YiRanMushroom/GTCEuAO#12]
[minecraft-exported-logs-2024-05-09T20-55-38.log](https://github.com/YiRanMushroom/GTCEuAO/files/15262568/minecraft-exported-logs-2024-05-09T20-55-38.log)
gtceu-1.20.1-1.2.1-build_642.jar

**Comment by YiRanMushroom** [comment]
Updated to make it compatible with GTM 1.2.2. Be aware that this version is non-production ready, all the changes haven't been thoroughly tested, and there are still many bugs of GTM 1.2.2.
