### ISSUE TITLE
问题 反馈

### ISSUE THREAD

**Issue by 3453890470** [YiRanMushroom/GTCEuAO#13]
https://mclo.gs/bFbygrI

**Comment by YiRanMushroom** [comment]
第一个是因为版本不对，第二个我感觉不是我的问题，你安装的什么整合包？好像是kubejs写的有问题，或者是mekanism的注册有问题

**Comment by 3453890470** [comment]
@YiRanMushroom

**Comment by 3453890470** [comment]
![image](https://github.com/YiRanMushroom/GTCEuAO/assets/104831916/125ea8d2-2662-44e0-b147-3bc578189055)

**Comment by 3453890470** [comment]
使用的Prism启动器

**Comment by 3453890470** [comment]
进入世界就会刷屏

**Comment by YiRanMushroom** [comment]
你描述的信息无法让我确定问题，你说用什么启动器，用其他的有没有问题？日志文件在那？你发的图片那些数字是什么？刷屏是什么意思？具体是什么现象？

**Comment by 3453890470** [comment]
GregTech Leisure

**Comment by 3453890470** [comment]
整合包是这个

**Comment by YiRanMushroom** [comment]
我测试没有任何问题

**Comment by 3453890470** [comment]
我还在找原因

**Comment by 3453890470** [comment]
加到老党里面就会这样子，开新党做了一些整合包自定义机器，也没有没问题

**Comment by 3453890470** [comment]
好像会把他包里的集成矿物处理厂爆掉
配方直接全无了

**Comment by 3453890470** [comment]
你的简单矿处的配方加上去好像就不会删掉了

**Comment by 3453890470** [comment]
我关了配方也移除

**Comment by YiRanMushroom** [comment]
我认为不是我的问题，你不发日志我没有任何办法

**Comment by 3453890470** [comment]
跳过上面那个问题好了

**Comment by 3453890470** [comment]
集成矿处好了，草

**Comment by 3453890470** [comment]
就这样吧

**Comment by YiRanMushroom** [comment]
可能是我这边的相关问题，之后排查一下。

**Comment by woetal** [comment]
> 集成矿处好了，草

我这边的集成矿石处理也爆掉了（悲）问问你是怎么解决的

**Comment by 3453890470** [comment]
![image](https://github.com/YiRanMushroom/GTCEuAO/assets/104831916/6cf08f55-6a52-478f-a16d-2aac19627d84)
关掉这仨

**Comment by YiRanMushroom** [comment]
感觉最多关掉第二个就行了吧，实在看不出来和第一个第三个有什么关系

**Comment by YiRanMushroom** [comment]
你说的爆掉了是什么问题，是消失了吗？我认为我的这个代码和集成的没关系呀

**Comment by 3453890470** [comment]
https://mclo.gs/IC4Krff
@YiRanMushroom 
gtceu版本1.2.3.a

**Comment by YiRanMushroom** [comment]
I'll take a look ltr

**Comment by 3453890470** [comment]
可以进入游戏，但是会在进入世界的时候崩溃

**Comment by YiRanMushroom** [comment]
Fixed in 3.3.2-build_43

**Comment by 3453890470** [comment]
ok

**Comment by 3453890470** [comment]
https://mclo.gs/w6hO1Oa

**Comment by 3453890470** [comment]
@YiRanMushroom

**Comment by YiRanMushroom** [comment]
I don't know WTF is going on. And I cannot reproduce this error. What modpack are you playing? Will this crash only occur when entering an existing world or it also occurs in a new world?

**Comment by YiRanMushroom** [comment]
Is it ATM9?

**Comment by 3453890470** [comment]
Add GE mod

**Comment by YiRanMushroom** [comment]
Can you try this https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.2.3.a-build_741 since I compiled in this version

**Comment by 3453890470** [comment]
Gregic-Energistics

**Comment by 3453890470** [comment]
只能使用整合包专供的GTM

**Comment by YiRanMushroom** [comment]
This looks pretty interest ngl

**Comment by YiRanMushroom** [comment]
Let me try to test on Gregic-Energistics

**Comment by YiRanMushroom** [comment]
Still have no idea what happened, can you tell me which gregtech version you are on?

**Comment by 3453890470** [comment]
1.2.3.a

**Comment by 3453890470** [comment]
可能是我使用了java18导致的？

**Comment by YiRanMushroom** [comment]
实在复现不了，我再想想办法

**Comment by 3453890470** [comment]
GTL更新了新版本

**Comment by 3453890470** [comment]
我试试

**Comment by 3453890470** [comment]
好像是我构建的ge有点问题

**Comment by YiRanMushroom** [comment]
现在反正这些东西bug都及其多，mod本身和附属处理bug都很吃力。我可能只能推荐多等一等，我也没什么好办法，这个bug我死活复现不了

**Comment by 3453890470** [comment]
你使用最新版GTL试试？

**Comment by 3453890470** [comment]
如何？

**Comment by YiRanMushroom** [comment]
没来得及搞，我这破电脑有问题，现在干什么都很麻烦。不过关于你说的哪个问题我好像看到了，（可能）是GTM的原生的问题，估计很快会修复。
https://github.com/GregTechCEu/GregTech-Modern/pull/1375

**Comment by YiRanMushroom** [comment]
也可能不是，别报太大希望

**Comment by 3453890470** [comment]
坏

**Comment by 3453890470** [comment]
不装你的mod就可以进GTL
的世界里面

**Comment by 3453890470** [comment]
真的不测测吗

**Comment by YiRanMushroom** [comment]
我马上看看，明天早上前给你答复。新世界可以进吗

**Comment by 3453890470** [comment]
我试试

**Comment by YiRanMushroom** [comment]
我说装上我的可以进吗

**Comment by YiRanMushroom** [comment]
GTL的GTM是有什么别的内容吗？为什么非要用那个？

**Comment by 3453890470** [comment]
拓展了更多kjs的接口

**Comment by 3453890470** [comment]
没有这个整合包里面好多脚本都用不了

**Comment by YiRanMushroom** [comment]
这个报错我认为是AE配方注册时出错，那个GTM有没有对于AE的总线和仓的什么改动？

**Comment by 3453890470** [comment]
不愿意写coremod 导致的

**Comment by 3453890470** [comment]
有改动的是GE

**Comment by 3453890470** [comment]
GE你试过没有问题的吗

**Comment by YiRanMushroom** [comment]
GE没有问题。

**Comment by 3453890470** [comment]
我还有好多ae附属

**Comment by YiRanMushroom** [comment]
我去试试，实在不行我试着加上try catch

**Comment by YiRanMushroom** [comment]
你把最新版GTLeisure的地址给我

**Comment by 3453890470** [comment]
要进群吗

**Comment by 3453890470** [comment]
456040951

**Comment by YiRanMushroom** [comment]
我去看一眼

**Comment by 3453890470** [comment]
https://mclo.gs/5yrQA8a

**Comment by 3453890470** [comment]
可能新一点日志

**Comment by YiRanMushroom** [comment]
还是之前问题

**Comment by 3453890470** [comment]
奇怪

**Comment by 3453890470** [comment]
难道是和什么ae附属冲突了吗

**Comment by 3453890470** [comment]
我在群里加你了

**Comment by YiRanMushroom** [comment]
我在尝试解决

**Comment by YiRanMushroom** [comment]
实在搞不清楚，没有他们写的源码我很难分析，我现在完全搞不懂发生了什么

**Comment by 3453890470** [comment]
我要一下仓库链接

**Comment by 3453890470** [comment]
https://github.com/nutant233/GregTech-Modern/tree/GTL_Fork

**Comment by 3453890470** [comment]
你看看群

**Comment by YiRanMushroom** [comment]
他们是不是把MEInputBus/Hatch给删掉了？

**Comment by YiRanMushroom** [comment]
ME的总线和接口

**Comment by 3453890470** [comment]
说是

**Comment by 3453890470** [comment]
是不是关掉相关配置就行了

**Comment by YiRanMushroom** [comment]
关掉这个应该就不崩了。AOConfigHolder.INSTANCE.recipes.AE2RecipeSupport

**Comment by 3453890470** [comment]
嗯，尝试中

**Comment by YiRanMushroom** [comment]
不过我应该能想办法自动取消，估计得用反射

**Comment by YiRanMushroom** [comment]
关掉后正常了吗

**Comment by 3453890470** [comment]
我看看

**Comment by 3453890470** [comment]
目前好了

**Comment by YiRanMushroom** [comment]
应该修好了，我马上push一下，不过我还是想测试一下再说

**Comment by 3453890470** [comment]
嗯，没有对应物品就会关掉？

**Comment by YiRanMushroom** [comment]
```
    @Inject(method = "init", at = @At("HEAD"), remap = false)
    private static void init(CallbackInfo ci){
        AERecipes.AE2BusAndHatchLoaded = true;
    }
```

```
if(AE2BusAndHatchLoaded) {...}
```

加了个判断

**Comment by YiRanMushroom** [comment]
之后没什么问题close了。

**Comment by YiRanMushroom** [comment]
现在建议更新版本然后把那个重新打开，要不然会少不少其他配方。

**Comment by 3453890470** [comment]
嗯，关闭吧，后面有啥问题私聊

**Comment by 3453890470** [comment]
@YiRanMushroom ，你有什么配置文件改了湿件的配方吗，我湿件基板合不出来

**Comment by YiRanMushroom** [comment]
好像有改变，我把一些消耗的改为不消耗了。好像是iv电路，luv泵，好像还有一个培养基。你看jei应该能看到配方呀

**Comment by 3453890470** [comment]
![image](https://github.com/YiRanMushroom/GTCEuAO/assets/104831916/a135105d-0075-4a58-b594-b89f63ab6bf3)
不合成

**Comment by YiRanMushroom** [comment]
你能用一般的input buffer试一下吗，我觉得是crafting io buffer的问题。

**Comment by YiRanMushroom** [comment]
关闭可以，但是有不少配方都会变。特别是晶体处理器的，晶体处理器我直接相当于删了一个产线。

**Comment by YiRanMushroom** [comment]
不对，让我看一下具体是哪个

**Comment by 3453890470** [comment]
ok，总成确实有点问题，我和gate说一下

**Comment by YiRanMushroom** [comment]
我加个配置专门控制这个吧。

**Comment by YiRanMushroom** [comment]
这个你应该说是有不消耗的物品，合成时存在流体可能会出现问题。不过现在也讲不清了，你的机器有没有并行？现在整个并行逻辑也有问题。

**Comment by YiRanMushroom** [comment]
可以更新到最新版本然后把recipes中的cheaperWetwareBoard关掉就行了
