### ISSUE TITLE
GTL添加gtceuao-1.20.1-3.5.2-build_62

### ISSUE THREAD

**Issue by tyuijhf** [YiRanMushroom/GTCEuAO#18]
电力高炉方块不能朝上是专门改的吗？

**Comment by tyuijhf** [comment]
有部分多方块可以旋转{翻转}摆放，所以我问问是专门改的不

**Comment by YiRanMushroom** [comment]
不是专门动的，不过我会看一下，我会尽量与GTM原版保持一致，如果原版有改动，我会想办法兼容。

**Comment by YiRanMushroom** [comment]
Fixed in [3.6.4-build_70](https://github.com/YiRanMushroom/GTCEuAO/releases/tag/3.6.4-build_70).
