### ISSUE TITLE
EBF

### ISSUE THREAD

**Issue by woetal** [YiRanMushroom/GTCEuAO#21]

**Comment by woetal** [comment]
EBF不工作，两个LV能源仓，铝粉，用1电路板没反应，关掉gtceuao正常

**Comment by woetal** [comment]
> EBF不工作，两个LV能源仓，铝粉，用1电路板没反应，关掉gtceuao正常

除非升压到HV才能跑铝粉的配方

**Comment by YiRanMushroom** [comment]
我抽空调查一下。

**Comment by YiRanMushroom** [comment]
试一下
https://github.com/YiRanMushroom/GTCEuAO/releases/tag/3.6.7L-build_73-modify_4

**Comment by woetal** [comment]
[minecraft-exported-logs-2024-07-19T12-50-53.log](https://github.com/user-attachments/files/16302206/minecraft-exported-logs-2024-07-19T12-50-53.log)

**Comment by woetal** [comment]
@YiRanMushroom

**Comment by YiRanMushroom** [comment]
你发的log里面不完整，且完全没有任何有效信息。
而且你应该新开一个issue如果有别的问题。

**Comment by YiRanMushroom** [comment]
而且如果你要说最新版本进不了存档，这不是我的问题，你不装这个模组也进不去。
