### ISSUE TITLE
Your module is not compatible with gtceu-1.20.1-1.1.3b, please update the module, thank you.

### ISSUE THREAD

**Issue by xiaolfc** [YiRanMushroom/GTCEuAO#4]
Your module is not compatible with gtceu-1.20.1-1.1.3b, please update the module, thank you.

**Comment by YiRanMushroom** [comment]
I have already noticed about this issue, however I was extremely busy these days. I may try to fix that next week during my reading week.

**Comment by xiaolfc** [comment]
Ok, could you please add the deleted function to speed up the processing speed of the single block machine in the next version? I really need it, thank you.

**Comment by YiRanMushroom** [comment]
It is not hard tbh but I am encountering some technical issues and I cannot compile the code, because gtceu changed some of their dependency. I just need to copy the code they deprecated it's not difficult.

**Comment by xiaolfc** [comment]
Ok,hope to see this feature in the next version of the module, thank you.

**Comment by YiRanMushroom** [comment]
Already ported deprecated code from gregtech in 2.2.0
