### ISSUE TITLE
不兼容gt1.1.4b

### ISSUE THREAD

**Issue by 3453890470** [YiRanMushroom/GTCEuAO#8]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.1.4.b

### Recipe Viewer Installed

No Recipe Viewer

### Environment

单人

### Cross-Mod Interaction

No

### Other Installed Mods

x

### Expected Behavior

x

### Actual Behavior

x

### Steps to Reproduce

安装gtceuao和gtm1.1.4.b

### Additional Information

和处理阵列相关，https://mclo.gs/0BN0zC4，这是错误报告

**Comment by YiRanMushroom** [comment]
我现在没有时间，等我放假，现在准备期末考

**Comment by YiRanMushroom** [comment]
已经更新好了
